### ISSUE TITLE
Could not pass event ProjectileHitEvent to KitchenSink v0.9.1

### ISSUE THREAD

**Issue by DOKDOR** [NerdNu/KitchenSink#38]
Keep getting this error when an arrow is fired.

[08:37:44 ERROR]: Could not pass event ProjectileHitEvent to KitchenSink v0.9.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:745) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.EntityArrow.t_(EntityArrow.java:224) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:584) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R1/entity/CraftArrow
        at nu.nerd.kitchensink.KitchenSinkListener.onProjectileHit(KitchenSinkListener.java:418) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        ... 14 more

**Comment by slide23** [comment]
KitchenSink has not been updated to support 1.8.3 yet. The current version supports only 1.8. I will be getting around to updating soon however.

**Comment by DOKDOR** [comment]
No problem. I just disabled the parts of the code that require updating and still works well. 
Would you be able to bump me either here or on IRC when you do update however, as I wouldn't mind having full functionality back. (Also not sure if it's been done yet, but all the dependencies are broken and make compiling this very hard)

**Comment by slide23** [comment]
0.9.2 - Added support for 1.8.3 - 20d6d5dcf1316c516c31fbae9b645c067a15f180
